name: nihonoari
description: A little Japanese Kana training

version: 1.8.0+13

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  kana_kit: ^2.0.0
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.2.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  fonts:
    - family: MP1P_MEDIUM
      fonts:
        - asset: assets/MPLUS1p-Medium.ttf
    - family: MP1P_REGULAR
      fonts:
        - asset: assets/MPLUS1p-Regular.ttf
    - family: MP1P_LIGHT
      fonts:
        - asset: assets/MPLUS1p-Light.ttf
  assets:
    - assets/LICENSES.txt
    - i18n/es.json
    - i18n/en.json
    - i18n/fr.json
    - i18n/uk.json
    - i18n/ru.json
    - i18n/tr.json
    - i18n/de.json
    - i18n/be.json
    - assets/data/hira.json
    - assets/data/kata.json

  uses-material-design: true
